INFO:root:informational message
ERROR:root:an error has happened!
INFO:root:informational message
ERROR:root:an error has happened!
ERROR:ex:Error!
Traceback (most recent call last):
  File "/media/mahedi/1E584CF8584CD067/FALSE/workspace/Python_Workspace/Python_101_Michael Driscoll/15_Logging/test2.py", line 8, in <module>
    raise RuntimeError
RuntimeError
ERROR:ex:Error!
Traceback (most recent call last):
  File "/media/mahedi/1E584CF8584CD067/FALSE/workspace/Python_Workspace/Python_101_Michael Driscoll/15_Logging/test2.py", line 8, in <module>
    raise RuntimeError
RuntimeError
